[outputFormats]

[outputFormats.Search]
baseName = 'index'
path = 'search'
isHTML = true
mediaType = 'text/html'
notAlternative = true

[outputFormats.SearchIndex]
baseName = 'search'
isPlainText = true
mediaType = 'application/json'
notAlternative = true

[module]
[module.hugoVersion]
extended = true

[[module.imports]]
path = "github.com/razonyang/hugo-mod-i18n-js"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-fuse-js"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-icons/vendors/bootstrap"

[params.hugopress.modules.search.hooks.head-end]

[params.hugopress.modules.search.hooks.body-end]

[params.search]
modal_container = "body"
stall_threshold = 300
case_sensitive = false
min_match_char_length = 1
location = 0
threshold = 0.6
distance = 100
ignore_location = false
shortcut_close = ["Escape"]
shortcut_search = ["Control", "k"]
paginate = 20
index_all_pages = true
expand_results_meta = false
