[outputFormats]
# RESERVED FOR SINGLE PAGE SEARCH.
# [outputFormats.Search]
# baseName = 'search'
# isHTML = true
# mediaType = 'text/html'
[outputFormats.SearchIndex]
baseName = 'search'
isPlainText = true
mediaType = 'application/json'

[module]
[module.hugoVersion]
extended = true

[[module.imports]]
path = "github.com/razonyang/hugo-mod-fuse-js"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-icons/vendors/bootstrap"

[params.hugopress.modules.search.hooks.head-end]

[params.hugopress.modules.search.hooks.body-end]

[params.search]
stall_threshold = 300
case_sensitive = false
min_match_char_length = 1
location = 0
threshold = 0.6
distance = 100
ignore_location = false
shortcut_close = ["Escape"]
shortcut_search = ["Control", "k"]
# input_placeholder = "Type to search"
