baseURL = 'http://example.org/'
languageCode = 'en'
title = 'Hugo Search Module'
theme = 'github.com/razonyang/hugo-mod-search'

[outputs]
home = ["HTML", "SearchIndex"]

[languages.en.params.search]
input_placeholder = "Type to search"

[languages.zh-hans.params.search]
input_placeholder = "请输入关键词"
